title:              Richard A. Kraaijenhagen    
description:        Founder of Owlin, vim user who's dreaming big about data.  
url:                riichard.com
signoff:            Richard A. Kraaijenhagen
disqus_shortname:   # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:     256634181194241
google_analytics:   # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          http://riichard.com/about
  - name:         Blog
    url:          http://riichard.com/
    external:     true
  - name:         Email
    url:          mailto: stdin@riichard.com
    external:     true
  - name:         GitHub
    url:          http://github.com/riichard
    external:     true
pygments:         true
permalink:        pretty 
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
