title:              Richard Kraaijenhagen    
description:        Founder of Owlin, vim user who's dreaming  big about data.  
url:                riichard.com
signoff:            Richard Kraaijenhagen
disqus_shortname:   # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:     # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics:   # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://riichard.com/
    external:     true
  - name:         Email
    url:          mailto:ping@riichard.com
    external:     true
  - name:         GitHub
    url:          http://github.com/riichard
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
